server.port=8080

spring.application.name=notifications-service

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/notifications_db}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=andreivarga0040317@gmail.com
spring.mail.password=tzue hynt vnpw mjxj 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET:dev-secret-not-for-production-12345678901234567890}
